export const tunes = [
  {
    id: "fairmont-gazebo",
    artist: "Fairmont",
    title: "Gazebo",
    year: 2004,
    releaseDate: "2004",
    label: "Bordercommunity",
    category: "evergreen",
    youtubeId: "Xy71oHnVrL0",
    text: "It was one of those very few records where I exactly remember when I heard it for the first time. It was the day before I had to do knee surgery. In my rooftop room, where electronic music played pretty much all day. My ambitions for becoming a decent soccer player were shredded and surgery was the only option to at least be able to do everything as an adult. Then I heard this jewel of a tune, \"Gazebo\" – one of James Holden's Bordercommunity label's best releases of all time, and the signature track of Fairmont. I was smiling when hearing it for the first time, goosebumps everywhere, and the feeling remained. When I left the door next morning approaching the hospital it still resonated with me, and crazy as it is, in the hospital after surgery I was craving to go back home to hear this fantastic tune again. In Spotify days no one can imagine how we \"CD guys\" did it. Much has been written about the track ever since, so not much needed to add aside from the above feeling: a great track wants you to return to it over and over again."
  },
  {
    id: "paris-healy-blue",
    artist: "Paris & Healy",
    title: "Blue",
    year: 2004,
    releaseDate: "2004",
    label: "",
    category: "evergreen",
    youtubeId: "Mz61bcKfKXQ",
    text: "It was the intro track Sasha played after James Zabiela did a fabulous warm-up for him at Pacha, Ibiza around 2004. I was there with my friend, also a big Sasha fan, and this track hit us hard. Cocteau Twins vocals and a bassline that's inviting you to dance and dream. I've played the track over and over again after finding it years later. Blue!"
  },
  {
    id: "dj-rolando-knights-of-the-jaguar",
    artist: "DJ Rolando",
    title: "Knights of the Jaguar",
    year: 1999,
    releaseDate: "1999",
    label: "Underground Resistance",
    category: "evergreen",
    youtubeId: "ZcC3vVh3cOE",
    text: "Not much to say about this gem – it's a classic and one of those absolute signature tracks that the electronic music I love stands for."
  },
  {
    id: "odds-parents-learn-to-fly-maceo-plex-remix",
    artist: "Odds Parents",
    title: "Learn To Fly (Maceo Plex Remix)",
    year: 2010,
    releaseDate: "2010",
    label: "",
    category: "evergreen",
    youtubeId: "3ErLuLJmrtY",
    text: "Maceo Plex is one of the biggest producers we have in the scene, and with this track he created an evergreen – one that fits many sets and carries both nostalgia and hope for the future. I've heard it many, many times, and it's a track I often listen to simply with my eyes closed, around people I love."
  },
  {
    id: "amtrac-civilian-world",
    artist: "Amtrac",
    title: "Civilian World",
    year: 2026,
    releaseDate: "March 13, 2026",
    dateAdded: "2026-06-24",
    label: "Anjunadeep",
    category: "new",
    youtubeId: "TFGyhVLXC50",
    text: "It's one of those Anjunadeep tracks, by one of those special artists, that instantly makes me smile. I play it repeatedly on sun-soaked days; it's rich in emotion and depth, working both for individual listening and on the dancefloor. Big Amtrac fan!"
  },
  {
    id: "m83-dont-save-us-from-the-flames-superpitcher-remix",
    artist: "M83",
    title: "Don't Save Us From The Flames (Superpitcher Remix)",
    year: 2006,
    releaseDate: "2006",
    label: "Kompakt",
    category: "evergreen",
    youtubeId: "xE2Qq4mzT3w",
    text: "Superpitcher, aka Aksel Schaufler – part of the famous Pachanga Boys – delivered a beauty that stands the test of time. 'A ghost is screaming your name...' Sasha played the track often, and so did I. It's one of those tracks that never gets old, that lights up every set, maybe the perfect outro. It's definitively an evergreen; if it were released today, it would still feel fresh."
  },
  {
    id: "luke-chable-melburn",
    artist: "Luke Chable",
    title: "Melburn",
    year: 2004,
    releaseDate: "2004",
    label: "Bedrock Records",
    category: "evergreen",
    youtubeId: "5ZbK__KkR2A",
    text: "Melburn, released in 2004 on John Digweed's Bedrock label, burns through you with passion, like a crackling log on a campfire. It carries a deep melancholy, paired with optimism, making it one of the absolute signature tracks of the progressive house scene. Things have gotten quieter around Luke Chable, but every time I return to Melburn, I'm reminded what a timeless track it is; the ten minutes fly by."
  },
  {
    id: "the-mfa-the-difference-it-makes",
    artist: "The MFA",
    title: "The Difference It Makes",
    year: 2003,
    releaseDate: "2003",
    label: "Balance Records",
    category: "evergreen",
    youtubeId: "4dcVUGkTmCA",
    text: "I remember it like it was yesterday. A good buddy of mine had the brand new Balance 005 compilation with him, and we're standing together in his classroom at school when he says, 'Hey Tommy, have you heard the new James Holden compilation yet?' He hits play, and a beautiful journey begins with 'The Difference It Makes.' The track has everything: a memorable bassline, carried by a heavenly melody, subtly distorted vocals, and the urge to never want it to stop. Much has been said about Holden's compilation already; for me, even after more than 20 years, it's still one of the best ever released. This track has a big part in that."
  },
  {
    id: "ame-rej",
    artist: "Âme",
    title: "Rej",
    year: 2005,
    releaseDate: "2005",
    label: "Innervisions",
    category: "evergreen",
    youtubeId: "BplYOLs9NSQ",
    text: "First heard at a Rave on Snow event when Toni Rios played it. It completely blew me away, and I knew instantly this tune would change everything."
  },
  {
    id: "argy-unreliable-virgin",
    artist: "Argy",
    title: "Unreliable Virgin",
    year: 2007,
    releaseDate: "2007",
    label: "Cocoon Recordings",
    category: "evergreen",
    youtubeId: "ZryObggQxVo",
    text: "Sven Väth played it over and over. Argy is a multifaceted producer; I liked his techno work much more than how he presents himself today."
  },
  {
    id: "nathan-fake-the-sky-was-pink-holden-remix",
    artist: "Nathan Fake",
    title: "The Sky Was Pink (Holden Remix)",
    year: 2004,
    releaseDate: "2004",
    label: "Border Community",
    category: "evergreen",
    youtubeId: "pN0QzsTbgmg",
    text: "First heard in a Timo Maas set at Il Muretto in Jesolo, Italy. This track is one of the best techno/progressive house tracks ever produced."
  },
  {
    id: "of-norway-smeigedag",
    artist: "Of Norway",
    title: "Smeigedag",
    year: 2023,
    releaseDate: "2023",
    label: "Connaisseur Recordings",
    category: "evergreen",
    youtubeId: "6nkN29edv3Y",
    text: "Smeigedag is what it feels like to stand on a sailboat, sun hitting your face just enough that you have to squint, but you keep your eyes open anyway because you don't want to miss it. The track has a rhythm and melody that absolutely stand out, and it's instantly recognizable. John Digweed has played it several times. The first time I heard it, I knew right away it would become something very special for me, long term."
  },
  {
    id: "lustral-everytime-nalin-kane-mix",
    artist: "Lustral",
    title: "Everytime (Nalin & Kane Mix)",
    year: 1997,
    releaseDate: "1997",
    label: "Hooj Choons",
    category: "evergreen",
    youtubeId: "-eJFbfMSArg",
    text: "This sits in the early, high-quality Oakenfold sound: a little trancy, but never overdone, always moving forward, with deep meaning underneath."
  },
  {
    id: "nalin-kane-beachball",
    artist: "Nalin & Kane",
    title: "Beachball",
    year: 1997,
    releaseDate: "1997",
    label: "Hooj Choons",
    category: "evergreen",
    youtubeId: "NcwrW231GEA",
    text: "A summer track that always sprays pure positive vibes."
  },
  {
    id: "royksopp-sordid-affair-maceo-plex-remix",
    artist: "Röyksopp",
    title: "Sordid Affair (Maceo Plex Remix)",
    year: 2014,
    releaseDate: "2014",
    label: "Dog Triumph",
    category: "evergreen",
    youtubeId: "004n7LTqIW0",
    text: "A track that enriches every set and delivers deep emotions. For me, one of the best remix works, ever."
  },
  {
    id: "new-jackson-the-night-mail",
    artist: "New Jackson",
    title: "The Night Mail",
    year: 2011,
    releaseDate: "2011",
    label: "Permanent Vacation",
    category: "evergreen",
    youtubeId: "3bmnYpQP__U",
    text: "New Jackson works with distorted vocoder voices that accompany many of his tracks and create a particular atmosphere and density. 'The Night Mail' is one of his signature tracks, and I love it deeply."
  },
  {
    id: "locked-groove-enigma",
    artist: "Locked Groove",
    title: "Enigma",
    year: 2014,
    releaseDate: "2014",
    label: "Hotflush Recordings",
    category: "evergreen",
    youtubeId: "E2UQ4hzmdGc",
    text: "Another track I first heard in Ibiza, in the original mix by John Talabot and in Seth Troxler's Scuba remix. It still moves me to this day: dark, driving, with a massive climax."
  },
  {
    id: "roger-sanchez-another-chance",
    artist: "Roger Sanchez",
    title: "Another Chance",
    year: 2001,
    releaseDate: "2001",
    label: "Defected Records",
    category: "evergreen",
    youtubeId: "rdlvPe959Ck",
    text: "One of the more commercial tracks in this selection, but it connects me to my early days in Ibiza and that feeling of pure freedom you only know in your youth and early adulthood."
  },
  {
    id: "robert-babicz-remote-kiss",
    artist: "Robert Babicz",
    title: "Remote Kiss",
    year: 2010,
    releaseDate: "2010",
    label: "Babiczstyle",
    category: "evergreen",
    youtubeId: "WZEQIjDpiAs",
    text: "Just the title alone is beautiful, and the track is just as enchanting. Babicz creates soundscapes and emotions like almost no one else, while always staying distant and subtle."
  },
  {
    id: "gabriel-ananda-maceo-plex-solitary-daze",
    artist: "Gabriel Ananda & Maceo Plex",
    title: "Solitary Daze",
    year: 2014,
    releaseDate: "2014",
    label: "Ellum Audio",
    category: "evergreen",
    youtubeId: "ib-lvhJnV0Q",
    text: "Gabriel Ananda and Maceo Plex created an evergreen here, one that fits many sets and carries both nostalgia and hope for the future."
  },
  {
    id: "benoit-sergio-let-me-count-the-ways",
    artist: "Benoit & Sergio",
    title: "Let Me Count The Ways",
    year: 2011,
    releaseDate: "2011",
    label: "Spectral Sound",
    category: "evergreen",
    youtubeId: "RJ2JVte9XcA",
    text: "An artful duo. 'Let Me Count The Ways' touched me deeply emotionally and was played around the globe by the likes of Sven Väth, Sasha & Digweed."
  },
  {
    id: "radio-slave-danton-eeprom-grindhouse",
    artist: "Radio Slave feat. Danton Eeprom",
    title: "Grindhouse (Danton Eeprom Remix)",
    year: 2008,
    releaseDate: "2008",
    label: "Rekids",
    category: "evergreen",
    youtubeId: "vbmqPX6Onqw",
    text: "I heard it in 2008 when Chris Liebing dropped the remix at Club Nova in Sattledt, and he tore the place apart. I still come back to it again and again, mostly because of that gloriously distorted percussion that drives the whole track."
  },
  {
    id: "eelke-kleijn-levensgenieter",
    artist: "Eelke Kleijn",
    title: "Levensgenieter",
    year: 2011,
    releaseDate: "2011",
    label: "Outside The Box Music",
    category: "evergreen",
    youtubeId: "FcS8myF0z4E",
    text: "It fits into every set that moves between house, progressive house, and techno, and it will tear the place apart every single time."
  },
  {
    id: "kolsch-goldfisch",
    artist: "Kölsch",
    title: "Goldfisch",
    year: 2013,
    releaseDate: "2013",
    label: "Kompakt",
    category: "evergreen",
    youtubeId: "lBaEUsJNpf0",
    text: "One of Kölsch's most famous tracks, instantly recognizable, full of joy, and a guaranteed highlight wherever it's played."
  },
  {
    id: "sascha-funke-mango-cookie-dj-koze-pink-moon-remix",
    artist: "Sascha Funke",
    title: "Mango Cookie (DJ Koze's Pink Moon Remix)",
    year: 2008,
    releaseDate: "2008",
    label: "BPitch Control",
    category: "evergreen",
    youtubeId: "2DvlihnVjYs",
    text: "A wonderfully complex, twelve-minute journey from DJ Koze, one of the true guarantors of quality in German electronic music."
  },
  {
    id: "estiva-via-balearia-extended-mix",
    artist: "Estiva",
    title: "Via Balearia (Extended Mix)",
    year: 2026,
    releaseDate: "June 12, 2026",
    dateAdded: "2026-06-26",
    label: "Colorize",
    category: "new",
    youtubeId: "cwOYcZLY7Pc",
    text: "Apart from the catchy name 'Via Balearia', this for-my-taste rather housey track carries an extreme amount of feeling. Somehow it catapults me back to Ibiza twenty years ago: hand on the back of the girl from Botany Bay, sitting at Café del Mar."
  },
  {
    id: "steve-lawler-sass",
    artist: "Steve Lawler",
    title: "Sass",
    year: 2026,
    releaseDate: "June 26, 2026",
    dateAdded: "2026-06-26",
    label: "Bedrock Records",
    category: "new",
    youtubeId: "KwYIG1j-LH8",
    text: "When Steve Lawler releases new stuff on Bedrock Records, it has my instant attention. And this track delivers something extraordinary. It's moving, with a highly engaging bassline and atmosphere; you simply want to dance. Lawler has been a defining force in house music since the early 90s, rising from illegal warehouse raves under the M42 motorway to residencies at Cream and Space Ibiza, where he earned the nickname 'King of Space.' A very strong record from a true veteran of the scene!"
  }
]